# Generated by Django 3.1.6 on 2021-02-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='stud_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
