# Generated by Django 3.1.6 on 2021-02-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentaddress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentaddress',
            unique_together={('country', 'city')},
        ),
    ]
