# Generated by Django 3.1.6 on 2021-02-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='working_period',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
