# Generated by Django 3.1.6 on 2021-02-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True)),
                ('about', models.TextField(blank=True, max_length=250, null=True)),
                ('certifications', models.ImageField(blank=True, null=True, unique=True, upload_to='images/')),
                ('period', models.DateField(null=True)),
                ('demo', models.URLField(blank=True, max_length=250, null=True, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='core.student')),
            ],
        ),
    ]
