# Generated by Django 3.1.6 on 2021-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='student', to='core.Skill'),
        ),
    ]
