# Generated by Django 3.1.6 on 2021-02-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_student_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='student_skills', to='core.Skill'),
        ),
    ]
