# Generated by Django 3.1.6 on 2021-02-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_companyaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('industry', models.CharField(max_length=100, null=True)),
                ('eligibility_criteria', models.TextField(null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('expiry', models.DateField()),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='images/jobs/')),
                ('gender_preference', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('np', 'No preference')], default='np', max_length=2)),
                ('employment_type', models.CharField(choices=[('p', 'Permanent'), ('p_t', 'PartTime'), ('Intern', 'Internship'), ('Contact', 'ContractBase')], max_length=25)),
                ('status', models.BooleanField(default=True, help_text='show to job recuritment Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company')),
            ],
        ),
    ]
