# Generated by Django 3.1.6 on 2021-02-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='followers',
            field=models.ManyToManyField(related_name='Company_followers', to='core.Student'),
        ),
    ]
