# Generated by Django 3.1.6 on 2021-02-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_company_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='Company_followers', to='core.Student'),
        ),
    ]
